name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@master

    - name: Composer install
      uses: php-actions/composer@v1

    - name: PHP-Scoper
      uses: php-actions/composer@v1
      with:
        command: global require humbug/php-scoper

    - name: PHP Scoper
      run: |
        php-scoper add-prefix
        cd build/ && composer dump-autoload

    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@master
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: cf7-cleverreach-integration
        GITHUB_WORKSPACE: "${{ GITHUB_WORKSPACE }}/build"
