name: Update assets/readme
on:
  push:
    branches:
    - master
    paths:
    - 'README.md'
    - '.wordpress-org/**'
jobs:
  master:
    name: Push to master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: WordPress.org plugin asset/readme update
      uses: pxlrbt/action-wordpress-plugin-asset-update@master
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: cf7-cleverreach-integration
        README_NAME: README.md
